-- Phase 9: Plot Profiles & Trust Badges

ALTER TABLE plots 
ADD COLUMN IF NOT EXISTS water_provided BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS organic_strict BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_chickens BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS willing_to_teach_chickens BOOLEAN DEFAULT FALSE;
